"""
chunking/strategies.py

Three chunking strategies for RAG indexing evaluation.
All strategies follow the same output schema and use fail-fast error handling.
"""

from __future__ import annotations

import re
import logging
from typing import Any

import nltk

logger = logging.getLogger(__name__)

# ── Token counting ────────────────────────────────────────────────────────────

def _approx_token_count(text: str) -> int:
    """Approximate token count by whitespace splitting. Fast, consistent."""
    return len(text.split())


# ── Chunk factory ──────────────────────────────────────────────────────────────

def _make_chunk(
    doc_id: str,
    strategy: str,
    index: int,
    text: str,
    heading: str | None = None,
) -> dict[str, Any]:
    text = text.strip()
    if not text:
        raise ValueError(
            f"Empty chunk generated by strategy '{strategy}' "
            f"for doc '{doc_id}' at index {index}. "
            "Check your document for long stretches of whitespace."
        )
    return {
        "chunk_id": f"{doc_id}__{strategy}__{index:04d}",
        "doc_id": doc_id,
        "strategy": strategy,
        "index": index,
        "text": text,
        "token_count": _approx_token_count(text),
        "char_count": len(text),
        "heading": heading,
    }


# ── Strategy 1: Fixed-Size ────────────────────────────────────────────────────

def fixed_size(
    text: str,
    doc_id: str,
    chunk_size: int = 256,
    overlap: int = 32,
) -> list[dict[str, Any]]:
    """
    Split document into fixed-size token windows with optional overlap.

    Args:
        text: Full document text.
        doc_id: Stable document identifier.
        chunk_size: Target number of tokens per chunk.
        overlap: Number of tokens to repeat at chunk boundaries.

    Returns:
        List of chunk dicts following the standard schema.

    Raises:
        ValueError: If chunk_size <= 0 or overlap >= chunk_size.
    """
    if chunk_size <= 0:
        raise ValueError(f"chunk_size must be > 0, got {chunk_size}")
    if overlap >= chunk_size:
        raise ValueError(
            f"overlap ({overlap}) must be less than chunk_size ({chunk_size})"
        )

    tokens = text.split()
    if not tokens:
        raise ValueError(f"Document '{doc_id}' produced no tokens after splitting.")

    chunks: list[dict[str, Any]] = []
    step = chunk_size - overlap
    start = 0
    index = 0

    while start < len(tokens):
        end = min(start + chunk_size, len(tokens))
        chunk_text = " ".join(tokens[start:end])
        chunks.append(_make_chunk(doc_id, "fixed", index, chunk_text))
        index += 1
        if end == len(tokens):
            break
        start += step

    logger.debug("fixed_size: doc='%s' → %d chunks", doc_id, len(chunks))
    return chunks


# ── Strategy 2: Sentence-Aware ────────────────────────────────────────────────

def _ensure_nltk_punkt() -> None:
    """Ensure NLTK punkt tokenizer is available. Fail fast if not."""
    try:
        nltk.data.find("tokenizers/punkt_tab")
    except LookupError:
        raise RuntimeError(
            "NLTK 'punkt_tab' tokenizer not found. "
            "Run: python -c \"import nltk; nltk.download('punkt_tab')\""
        )


def sentence_aware(
    text: str,
    doc_id: str,
    target_tokens: int = 256,
    overlap_sentences: int = 1,
) -> list[dict[str, Any]]:
    """
    Group sentences into chunks targeting a token count.
    Never splits mid-sentence. Adds sentence-level overlap at boundaries.

    Args:
        text: Full document text.
        doc_id: Stable document identifier.
        target_tokens: Soft upper bound on tokens per chunk.
        overlap_sentences: Number of trailing sentences from the previous
                           chunk to prepend to the current chunk.

    Returns:
        List of chunk dicts following the standard schema.

    Raises:
        RuntimeError: If NLTK punkt data is missing.
        ValueError: If document produces no sentences.
    """
    _ensure_nltk_punkt()

    sentences = nltk.sent_tokenize(text)
    if not sentences:
        raise ValueError(f"Document '{doc_id}' produced no sentences after tokenization.")

    chunks: list[dict[str, Any]] = []
    current_sents: list[str] = []
    current_tokens = 0
    index = 0

    for sent in sentences:
        sent_tokens = _approx_token_count(sent)
        # If adding this sentence would exceed target and we already have content, flush
        if current_tokens + sent_tokens > target_tokens and current_sents:
            chunk_text = " ".join(current_sents)
            chunks.append(_make_chunk(doc_id, "sentence", index, chunk_text))
            index += 1
            # Carry over the last N sentences as overlap
            current_sents = current_sents[-overlap_sentences:] if overlap_sentences > 0 else []
            current_tokens = sum(_approx_token_count(s) for s in current_sents)

        current_sents.append(sent)
        current_tokens += sent_tokens

    # Flush remainder
    if current_sents:
        chunk_text = " ".join(current_sents)
        chunks.append(_make_chunk(doc_id, "sentence", index, chunk_text))

    if not chunks:
        raise ValueError(
            f"sentence_aware produced 0 chunks for doc '{doc_id}'. "
            "Check document content and target_tokens setting."
        )

    logger.debug("sentence_aware: doc='%s' → %d chunks", doc_id, len(chunks))
    return chunks


# ── Strategy 3: Semantic ──────────────────────────────────────────────────────

# Matches Markdown headings: #, ##, ###, ####
_HEADING_RE = re.compile(r"^(#{1,4})\s+(.+)$", re.MULTILINE)

# Matches blank lines separating paragraphs
_PARAGRAPH_SPLIT_RE = re.compile(r"\n{2,}")


def _detect_sections(text: str) -> list[dict[str, str | None]]:
    """
    Split document into sections based on Markdown headings.
    Falls back to paragraph splitting if no headings are found.

    Returns:
        List of dicts with keys: 'heading' (str | None), 'body' (str)
    """
    heading_positions = [(m.start(), m.group(0), m.group(2)) for m in _HEADING_RE.finditer(text)]

    if not heading_positions:
        # No headings: fall back to paragraph splitting
        paragraphs = [p.strip() for p in _PARAGRAPH_SPLIT_RE.split(text) if p.strip()]
        return [{"heading": None, "body": para} for para in paragraphs]

    sections: list[dict[str, str | None]] = []

    # Content before first heading
    first_pos = heading_positions[0][0]
    preamble = text[:first_pos].strip()
    if preamble:
        sections.append({"heading": None, "body": preamble})

    for i, (pos, heading_line, heading_text) in enumerate(heading_positions):
        next_pos = heading_positions[i + 1][0] if i + 1 < len(heading_positions) else len(text)
        # Body is everything after the heading line until next heading
        body_start = pos + len(heading_line)
        body = text[body_start:next_pos].strip()
        sections.append({"heading": heading_text, "body": body})

    return sections


def semantic(
    text: str,
    doc_id: str,
    max_tokens: int = 512,
) -> list[dict[str, Any]]:
    """
    Split document on heading or paragraph boundaries.
    Merges small sections into a single chunk until max_tokens is reached.

    Args:
        text: Full document text.
        doc_id: Stable document identifier.
        max_tokens: Maximum tokens per chunk. Large sections are split
                    at paragraph boundaries if they exceed this limit.

    Returns:
        List of chunk dicts following the standard schema.

    Raises:
        ValueError: If document produces no sections.
    """
    sections = _detect_sections(text)
    if not sections:
        raise ValueError(
            f"semantic: doc '{doc_id}' produced no sections. "
            "Ensure the document has content."
        )

    chunks: list[dict[str, Any]] = []
    current_parts: list[str] = []
    current_heading: str | None = None
    current_tokens = 0
    index = 0

    for section in sections:
        heading = section["heading"]
        body = section["body"]
        if not body:
            continue

        body_tokens = _approx_token_count(body)

        # If this section alone exceeds max_tokens, flush current buffer first,
        # then split the large section into sub-chunks
        if body_tokens > max_tokens:
            if current_parts:
                chunk_text = "\n\n".join(current_parts)
                chunks.append(_make_chunk(doc_id, "semantic", index, chunk_text, current_heading))
                index += 1
                current_parts = []
                current_tokens = 0
                current_heading = None

            # Sub-chunk the oversized section using paragraph splits
            sub_paragraphs = [p.strip() for p in _PARAGRAPH_SPLIT_RE.split(body) if p.strip()]
            sub_parts: list[str] = []
            sub_tokens = 0
            for para in sub_paragraphs:
                para_tokens = _approx_token_count(para)
                if sub_tokens + para_tokens > max_tokens and sub_parts:
                    chunk_text = "\n\n".join(sub_parts)
                    chunks.append(_make_chunk(doc_id, "semantic", index, chunk_text, heading))
                    index += 1
                    sub_parts = []
                    sub_tokens = 0
                sub_parts.append(para)
                sub_tokens += para_tokens
            if sub_parts:
                chunk_text = "\n\n".join(sub_parts)
                chunks.append(_make_chunk(doc_id, "semantic", index, chunk_text, heading))
                index += 1
            continue

        # If merging this section would exceed max_tokens, flush first
        if current_tokens + body_tokens > max_tokens and current_parts:
            chunk_text = "\n\n".join(current_parts)
            chunks.append(_make_chunk(doc_id, "semantic", index, chunk_text, current_heading))
            index += 1
            current_parts = []
            current_tokens = 0
            current_heading = None

        # Start tracking the first heading of a new merged group
        if not current_parts and heading:
            current_heading = heading

        current_parts.append(body)
        current_tokens += body_tokens

    # Flush remainder
    if current_parts:
        chunk_text = "\n\n".join(current_parts)
        chunks.append(_make_chunk(doc_id, "semantic", index, chunk_text, current_heading))

    if not chunks:
        raise ValueError(
            f"semantic produced 0 chunks for doc '{doc_id}'. "
            "Check document content and max_tokens setting."
        )

    logger.debug("semantic: doc='%s' → %d chunks", doc_id, len(chunks))
    return chunks
